// PERMIVIO — authoritative government GIS lookups (server-only).
//
// These are real municipal/federal boundary databases, queried directly:
//   • U.S. Census Bureau Geocoder + TIGER geographies — the authoritative
//     record of whether a point falls inside an incorporated place (city /
//     town / village) or in unincorporated county territory, plus the county,
//     county subdivision (township/MCD), state, tract and block.
//   • FCC Census Block API — independent county/state confirmation from the
//     same 2020 TIGER geography, used as a cross-check and fallback.
//   • FEMA National Flood Hazard Layer — flood zone at the parcel point.
//
// Nothing here is generated by a model. Every value returned is either read
// from an official service response or reported as unavailable. When a
// service cannot be reached, the field is `null` and the caller must treat
// the determination as unconfirmed — never assume the postal city controls.

export type CensusPlace = {
  name: string;
  basename: string;
  geoid: string;
  /** TIGER legal/statistical area description code (25 = city, 43 = town, ...). */
  lsad: string | null;
  /** FUNCSTAT "A"/"B"/"C"/"F"/"G"/"N": active vs. statistical/inactive entity. */
  funcstat: string | null;
};

export type CensusGeography = {
  matchedAddress: string | null;
  lat: number | null;
  lng: number | null;
  /** Incorporated place containing the point, or null when unincorporated. */
  place: CensusPlace | null;
  /** Minor civil division / township, where states use them. */
  countySubdivision: CensusPlace | null;
  county: string | null;
  countyFips: string | null;
  state: string | null;
  stateAbbr: string | null;
  tract: string | null;
  block: string | null;
  sourceUrl: string;
};

export type FloodZone = {
  zone: string;
  subtype: string | null;
  /** FEMA "T"/"F": inside a Special Flood Hazard Area. */
  sfha: boolean | null;
  firmPanel: string | null;
  sourceUrl: string;
};

export type FccArea = {
  countyName: string | null;
  countyFips: string | null;
  stateCode: string | null;
  blockFips: string | null;
  sourceUrl: string;
};

/** One authoritative record, shaped for the agent evidence pipeline. */
export type GovEvidenceItem = {
  source_key: string;
  url: string;
  title: string;
  retrieved: boolean;
  excerpt: string;
  /** Matches SourceType in the agent framework. */
  kind: "official_gis_or_parcel_data" | "official_zoning_map";
};

export type AuthoritativeGeography = {
  census: CensusGeography | null;
  fcc: FccArea | null;
  flood: FloodZone | null;
  /** Deterministic control determination derived from the boundary data. */
  determination: {
    place_in_control: string | null;
    incorporation_status:
      | "inside_municipal_limits"
      | "unincorporated_county"
      | "different_municipality_than_postal_city"
      | "undetermined";
    postal_city_is_controlling: boolean | null;
    note: string;
    /** True only when a real boundary service answered. */
    authoritative: boolean;
  };
  evidence: GovEvidenceItem[];
  /** Services that could not be reached on this run. */
  unavailable: string[];
};

const CENSUS_BENCHMARK = "Public_AR_Current";
const CENSUS_VINTAGE = "Current_Current";
const CENSUS_LAYERS = "Incorporated Places,County Subdivisions,Counties,States,Census Tracts,2020 Census Blocks";

async function getJson<T>(url: string, timeoutMs = 15000): Promise<T> {
  const resp = await fetch(url, {
    signal: AbortSignal.timeout(timeoutMs),
    headers: { Accept: "application/json", "User-Agent": "Permivio/1.0 (permitting research)" },
  });
  if (!resp.ok) throw new Error(`${resp.status} ${resp.statusText}`);
  return (await resp.json()) as T;
}

type CensusGeoRow = Record<string, unknown>;
type CensusResponse = {
  result?: {
    addressMatches?: Array<{
      matchedAddress?: string;
      coordinates?: { x: number; y: number };
      geographies?: Record<string, CensusGeoRow[]>;
    }>;
    geographies?: Record<string, CensusGeoRow[]>;
  };
};

function str(row: CensusGeoRow | undefined, key: string): string | null {
  const v = row?.[key];
  return typeof v === "string" && v.trim() ? v.trim() : typeof v === "number" ? String(v) : null;
}

function toPlace(row: CensusGeoRow | undefined): CensusPlace | null {
  if (!row) return null;
  const name = str(row, "NAME");
  const geoid = str(row, "GEOID");
  if (!name || !geoid) return null;
  return {
    name,
    basename: str(row, "BASENAME") ?? name,
    geoid,
    lsad: str(row, "LSADC"),
    funcstat: str(row, "FUNCSTAT"),
  };
}

function readGeographies(geo: Record<string, CensusGeoRow[]> | undefined, sourceUrl: string, base: Partial<CensusGeography>): CensusGeography {
  const pick = (label: string) => {
    const key = Object.keys(geo ?? {}).find((k) => k.toLowerCase() === label.toLowerCase());
    return key ? (geo ?? {})[key]?.[0] : undefined;
  };
  const county = pick("Counties");
  const state = pick("States");
  return {
    matchedAddress: base.matchedAddress ?? null,
    lat: base.lat ?? null,
    lng: base.lng ?? null,
    place: toPlace(pick("Incorporated Places")),
    countySubdivision: toPlace(pick("County Subdivisions")),
    county: str(county, "NAME"),
    countyFips: str(county, "GEOID"),
    state: str(state, "NAME"),
    stateAbbr: str(state, "STUSAB"),
    tract: str(pick("Census Tracts"), "GEOID"),
    block: str(pick("2020 Census Blocks"), "GEOID"),
    sourceUrl,
  };
}

/** Address → TIGER geographies (authoritative corporate-limit determination). */
export async function censusGeographiesByAddress(address: string): Promise<CensusGeography | null> {
  const url =
    `https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress?address=${encodeURIComponent(address)}` +
    `&benchmark=${CENSUS_BENCHMARK}&vintage=${CENSUS_VINTAGE}&layers=${encodeURIComponent(CENSUS_LAYERS)}&format=json`;
  const j = await getJson<CensusResponse>(url);
  const m = j.result?.addressMatches?.[0];
  if (!m) return null;
  return readGeographies(m.geographies, url, {
    matchedAddress: m.matchedAddress ?? null,
    lat: m.coordinates?.y ?? null,
    lng: m.coordinates?.x ?? null,
  });
}

/** Coordinates → TIGER geographies. Used when the address does not match. */
export async function censusGeographiesByPoint(lat: number, lng: number): Promise<CensusGeography | null> {
  const url =
    `https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=${lng}&y=${lat}` +
    `&benchmark=${CENSUS_BENCHMARK}&vintage=${CENSUS_VINTAGE}&layers=${encodeURIComponent(CENSUS_LAYERS)}&format=json`;
  const j = await getJson<CensusResponse>(url);
  const geo = j.result?.geographies;
  if (!geo) return null;
  return readGeographies(geo, url, { lat, lng });
}

export async function fccArea(lat: number, lng: number): Promise<FccArea | null> {
  const url = `https://geo.fcc.gov/api/census/area?lat=${lat}&lon=${lng}&format=json`;
  const j = await getJson<{
    results?: Array<{ county_name?: string; county_fips?: string; state_code?: string; block_fips?: string }>;
  }>(url);
  const r = j.results?.[0];
  if (!r) return null;
  return {
    countyName: r.county_name ?? null,
    countyFips: r.county_fips ?? null,
    stateCode: r.state_code ?? null,
    blockFips: r.block_fips ?? null,
    sourceUrl: url,
  };
}

/** FEMA National Flood Hazard Layer — flood zone at the point. */
export async function femaFloodZone(lat: number, lng: number): Promise<FloodZone | null> {
  const geometry = encodeURIComponent(JSON.stringify({ x: lng, y: lat, spatialReference: { wkid: 4326 } }));
  const url =
    `https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28/query?geometry=${geometry}` +
    `&geometryType=esriGeometryPoint&inSR=4326&spatialRel=esriSpatialRelIntersects` +
    `&outFields=FLD_ZONE,ZONE_SUBTY,SFHA_TF,DFIRM_ID,FIRM_PAN&returnGeometry=false&f=json`;
  const j = await getJson<{ features?: Array<{ attributes?: Record<string, unknown> }> }>(url, 20000);
  const a = j.features?.[0]?.attributes;
  if (!a) return null;
  const zone = typeof a['FLD_ZONE'] === "string" ? a['FLD_ZONE'] : null;
  if (!zone) return null;
  const sfha = typeof a['SFHA_TF'] === "string" ? a['SFHA_TF'].toUpperCase() === "T" : null;
  return {
    zone,
    subtype: typeof a['ZONE_SUBTY'] === "string" ? a['ZONE_SUBTY'] : null,
    sfha,
    firmPanel: typeof a['FIRM_PAN'] === "string" ? a['FIRM_PAN'] : null,
    sourceUrl: url,
  };
}

/** Census LSAD code → readable entity type, so "city" vs "town" is not guessed. */
function placeKind(lsad: string | null): string {
  const map: Record<string, string> = {
    "21": "borough",
    "25": "city",
    "43": "town",
    "47": "village",
    "471": "village",
    "44": "township",
    "57": "CDP (census designated place — statistical only)",
  };
  return (lsad && map[lsad]) || "incorporated place";
}

/**
 * Query every reachable authoritative boundary service for one point and
 * derive the controlling-place determination from the data alone.
 */
export async function resolveAuthoritativeGeography(input: {
  address: string;
  lat: number;
  lng: number;
  postalCity: string | null;
}): Promise<AuthoritativeGeography> {
  const unavailable: string[] = [];

  let census: CensusGeography | null = null;
  try {
    census = await censusGeographiesByAddress(input.address);
    if (!census) census = await censusGeographiesByPoint(input.lat, input.lng);
  } catch {
    try {
      census = await censusGeographiesByPoint(input.lat, input.lng);
    } catch {
      census = null;
    }
  }
  if (!census) unavailable.push("U.S. Census Bureau TIGER geographies");

  const [fccRes, floodRes] = await Promise.allSettled([
    fccArea(input.lat, input.lng),
    femaFloodZone(input.lat, input.lng),
  ]);
  const fcc = fccRes.status === "fulfilled" ? fccRes.value : null;
  if (!fcc) unavailable.push("FCC Census Block API");
  const flood = floodRes.status === "fulfilled" ? floodRes.value : null;
  if (!flood) unavailable.push("FEMA National Flood Hazard Layer");

  const evidence: GovEvidenceItem[] = [];
  const postal = (input.postalCity ?? "").trim().toLowerCase();

  let determination: AuthoritativeGeography["determination"] = {
    place_in_control: null,
    incorporation_status: "undetermined",
    postal_city_is_controlling: null,
    note:
      "No official boundary service could be reached for this parcel, so corporate-limit status is unconfirmed. The mailing address does not establish jurisdiction — confirm with the county GIS/assessor and the municipal planning office.",
    authoritative: false,
  };

  if (census) {
    // A place with FUNCSTAT "S"/"N" or LSAD 57 is statistical, not governing.
    const p = census.place;
    const statistical = !!p && (p.lsad === "57" || p.funcstat === "S");
    const governing = p && !statistical ? p : null;
    const placeName = governing ? governing.name : null;
    const county = census.county;

    if (governing) {
      const sameAsPostal = !!postal && governing.basename.toLowerCase() === postal;
      determination = {
        place_in_control: placeName,
        incorporation_status: sameAsPostal ? "inside_municipal_limits" : "different_municipality_than_postal_city",
        postal_city_is_controlling: sameAsPostal,
        note: sameAsPostal
          ? `Census TIGER boundaries place this point inside the corporate limits of ${governing.name} (${placeKind(governing.lsad)}, GEOID ${governing.geoid}) in ${county ?? "the county of record"}. The municipality is the land-use authority for functions it has not delegated; county, state and utility authorities still apply.`
          : `Census TIGER boundaries place this point inside ${governing.name} (${placeKind(governing.lsad)}, GEOID ${governing.geoid}), which is NOT the postal city on the mailing address${input.postalCity ? ` (${input.postalCity})` : ""}. Permit applications go to ${governing.name}, not the mailing city.`,
        authoritative: true,
      };
    } else {
      determination = {
        place_in_control: county,
        incorporation_status: "unincorporated_county",
        postal_city_is_controlling: false,
        note: `Census TIGER boundaries show this point is NOT inside any incorporated municipality${statistical && p ? ` — "${p.name}" is a census designated place, a statistical area with no government` : ""}. ${county ?? "The county"} is the governing land-use authority for unincorporated territory; the postal city${input.postalCity ? ` (${input.postalCity})` : ""} has no permitting authority here.`,
        authoritative: true,
      };
    }

    evidence.push({
      source_key: "G1",
      url: census.sourceUrl,
      title: "U.S. Census Bureau Geocoder — TIGER incorporated place, county subdivision, county and state boundaries at the site",
      retrieved: true,
      kind: "official_gis_or_parcel_data",
      excerpt: [
        `Matched address: ${census.matchedAddress ?? "(point query)"}`,
        `Coordinates: ${census.lat ?? input.lat}, ${census.lng ?? input.lng}`,
        `Incorporated place containing the point: ${p ? `${p.name} (LSAD ${p.lsad ?? "?"} = ${placeKind(p.lsad)}, FUNCSTAT ${p.funcstat ?? "?"}, GEOID ${p.geoid})` : "NONE — the point is not inside any incorporated place (unincorporated territory)"}`,
        `County subdivision / MCD: ${census.countySubdivision ? `${census.countySubdivision.name} (GEOID ${census.countySubdivision.geoid})` : "none reported"}`,
        `County: ${census.county ?? "unknown"} (FIPS ${census.countyFips ?? "?"})`,
        `State: ${census.state ?? "unknown"} (${census.stateAbbr ?? "?"})`,
        `Census tract: ${census.tract ?? "unknown"} | 2020 block: ${census.block ?? "unknown"}`,
        `Determination derived from these boundaries: ${determination.incorporation_status}.`,
      ].join("\n"),
    });
  }

  if (fcc) {
    evidence.push({
      source_key: "G2",
      url: fcc.sourceUrl,
      title: "FCC Census Block API — county and state confirmation at the site coordinates",
      retrieved: true,
      kind: "official_gis_or_parcel_data",
      excerpt: `County: ${fcc.countyName ?? "unknown"} (FIPS ${fcc.countyFips ?? "?"})\nState: ${fcc.stateCode ?? "unknown"}\n2020 census block: ${fcc.blockFips ?? "unknown"}`,
    });
  }

  if (flood) {
    evidence.push({
      source_key: "G3",
      url: flood.sourceUrl,
      title: "FEMA National Flood Hazard Layer — effective flood zone at the site coordinates",
      retrieved: true,
      kind: "official_zoning_map",
      excerpt: `FEMA flood zone: ${flood.zone}${flood.subtype ? ` (${flood.subtype})` : ""}\nSpecial Flood Hazard Area: ${flood.sfha === null ? "not reported" : flood.sfha ? "YES — floodplain development permit and elevation requirements apply" : "no"}\nFIRM panel: ${flood.firmPanel ?? "not reported"}`,
    });
  }

  return { census, fcc, flood, determination, evidence, unavailable };
}
