/**
 * Researched statewide code adoptions (official sources, researched 2026-09-30).
 * `primary` = read from the adopting agency / official register. Non-primary mirrors
 * (LII, UpCodes, third-party PDFs) are never marked Verified.
 * There are no "national" amendments — model codes are adopted (and amended) state by state,
 * and many states allow local amendments.
 */
export type AdoptionDiscipline = "building" | "electrical" | "fire";
export type StateAdoption = {
  state: string; discipline: AdoptionDiscipline; code: string | null; effective: string | null;
  org: string; url: string; quote: string; primary: boolean; note?: string;
};
export type LocalAmendmentPolicy = { state: string; policy: "permitted" | "limited" | "not_permitted" | "local_codes_only" | "unknown"; text: string; url: string; primary: boolean };

export const RESEARCHED_AS_OF = "2026-09-30";

export const STATE_ADOPTIONS: StateAdoption[] = [
  { state: "FL", discipline: "electrical", code: "NFPA 70 (NEC) 2023, by reference in the FBC 8th Edition", effective: "2023-12-31", org: "Florida Building Commission", url: "https://www.floridabuilding.org/fbc/thecode/2026_Code_Development/Pre_December_2025_FBC/Electrical_detail.pdf", quote: "adoption of NFPA 70-23, including all published TIAs", primary: false, note: "From a Florida Building Commission code-development record, not the adopted code text. Confirm against FBC Chapter 35 (Referenced Standards)." },
  { state: "TX", discipline: "electrical", code: "NEC 2023", effective: "2023-09-01", org: "Texas Department of Licensing and Regulation", url: "https://www.tdlr.texas.gov/ELECTRICIANS/compliance-guide.htm", quote: "TDLR has adopted the National Electric Code 2023 Edition... It became effective September 1, 2023.", primary: true },
  { state: "TX", discipline: "building", code: null, effective: null, org: "Texas Department of Licensing and Regulation", url: "https://www.tdlr.texas.gov/ELECTRICIANS/compliance-guide.htm", quote: "", primary: false, note: "Texas has no single statewide building or fire code for most jurisdictions — cities and counties adopt their own editions." },
  { state: "MD", discipline: "building", code: "2021 IBC / IRC / IECC (Maryland Building Performance Standards, COMAR 09.12.51)", effective: "2023-05-29", org: "Maryland Department of Labor", url: "https://www.labor.maryland.gov/labor/build/buildcodes.shtml", quote: "2021 International Building Code... 2021 International Residential Code... 2021 International Energy Conservation Code", primary: true, note: "Effective date taken from a secondary timeline." },
  { state: "MD", discipline: "electrical", code: null, effective: null, org: "Maryland Department of Labor", url: "https://www.labor.maryland.gov/labor/build/buildcodematrix.pdf", quote: "Electrical (3) local jurisdiction (locally adopted)", primary: true, note: "No single statewide NEC for private buildings — the local jurisdiction's adopted edition applies." },
  { state: "MD", discipline: "fire", code: "NFPA 1 and NFPA 101, 2024 editions (State Fire Prevention Code)", effective: null, org: "Maryland Department of Labor (code matrix)", url: "https://www.labor.maryland.gov/labor/build/buildcodematrix.pdf", quote: "not applicable to one- and two-family dwellings and buildings located in Baltimore City", primary: true, note: "Not applicable to one- and two-family dwellings or Baltimore City." },
  { state: "DC", discipline: "building", code: "2017 DC Construction Codes (2015 ICC family)", effective: "2020-05-29", org: "DC Department of Buildings", url: "https://dob.dc.gov/node/1615636", quote: "The 2017 DC Construction Code takes effect on May 29, 2020.", primary: true },
  { state: "DC", discipline: "electrical", code: "NEC 2014, as amended (2017 DC Construction Codes)", effective: "2020-05-29", org: "DC Department of Buildings", url: "https://up.codes/viewer/district-of-columbia/ibc-2015/chapter/new_1/administration-and-enforcement", quote: "The National Electrical Code (2014) published by the National Fire Protection Association", primary: false },
  { state: "DC", discipline: "fire", code: "2015 IFC as amended (DC Fire Code 2017, 12-H DCMR)", effective: "2020-05-29", org: "DC Department of Buildings", url: "https://up.codes/viewer/district-of-columbia/ifc-2015/chapter/1/scope-and-enforcement", quote: "shall consist of the 2015 edition of the International Fire Code as amended", primary: false },
  { state: "VA", discipline: "building", code: "2021 Virginia Uniform Statewide Building Code", effective: "2024-01-18", org: "Virginia DHCD", url: "https://www.dhcd.virginia.gov/node/582", quote: "The effective date of the 2021 Uniform Statewide Building Code... is Jan. 18, 2024.", primary: true },
  { state: "VA", discipline: "electrical", code: "NEC 2020 (via 2021 USBC)", effective: "2024-01-18", org: "Virginia DHCD", url: "https://www.dhcd.virginia.gov/node/582", quote: "Virginia adopted the 2021 I-codes... and the 2020 National Electrical Code.", primary: true },
  { state: "VA", discipline: "fire", code: "2021 Virginia Statewide Fire Prevention Code (2021 IFC)", effective: "2024-01-18", org: "Virginia DHCD (copy published by Fluvanna County)", url: "https://www.fluvannacounty.org/sites/default/files/fileattachments/building_inspections/page/511/2021-virginia-statewide-fire-prevention-code.pdf", quote: "Effective Date: January 18, 2024", primary: false },
  { state: "NC", discipline: "building", code: "2024 North Carolina State Building Code", effective: "2025-07-01", org: "NC Office of State Fire Marshal", url: "https://www.ncbarch.org/wp-content/uploads/2025/01/2024-1212-Effective-date-of-the-2024-North-Carolina-State-Building-Code.pdf", quote: "The 2024 North Carolina State Building Code is effective on 7/1/25.", primary: false, note: "Office of State Fire Marshal notice, as republished by the NC Board of Architecture." },
  { state: "NC", discipline: "electrical", code: "2023 NC Electrical Code (NEC 2023 with NC amendments)", effective: "2025-07-01", org: "NC Office of State Fire Marshal", url: "https://www.ncbarch.org/wp-content/uploads/2025/01/2024-1212-Effective-date-of-the-2024-North-Carolina-State-Building-Code.pdf", quote: "2023 North Carolina Electrical Code (2023 NFPA 70 National Electrical Code with NC Amendments)", primary: false },
  { state: "NC", discipline: "fire", code: null, effective: null, org: "NC Office of State Fire Marshal", url: "https://www.ncosfm.gov/codes", quote: "", primary: false, note: "Fire code edition in the 2024 package was not confirmed." },
  { state: "MA", discipline: "building", code: "780 CMR 10th Edition (2021 I-Codes)", effective: "2024-10-11", org: "Massachusetts BBRS", url: "https://www.mass.gov/news/10th-edition-of-the-state-building-code-board-of-building-regulations-and-standards", quote: "Effective October 11, 2024, the 10th Edition of the State Building Code will take effect.", primary: true },
  { state: "MA", discipline: "electrical", code: "527 CMR 12.00 (NEC 2026)", effective: "2026-04-24", org: "Massachusetts Board of Fire Prevention Regulations", url: "https://www.mass.gov/info-details/massachusetts-electrical-code", quote: "based on the 2026 edition of NFPA 70... effective as of April 24, 2026", primary: true },
  { state: "MA", discipline: "fire", code: "527 CMR 1.00 (NFPA 1, 2021)", effective: "2022-12-09", org: "Massachusetts Department of Fire Services", url: "https://www.mass.gov/info-details/massachusetts-fire-code", quote: "The current State Fire Code went into effect on December 9, 2022.", primary: true },
  { state: "NH", discipline: "building", code: "NH State Building Code (2024 I-Codes; IECC 2018)", effective: "2026-07-01", org: "NH State Building Code Review Board (copy published by Town of Merrimack)", url: "https://www.merrimacknh.gov/DocumentCenter/View/5723/2024-NH-State-Building-Code", quote: "updating six of the adopted model codes to the 2024 edition, excluding the 2018 IECC and the 2023 NEC", primary: false },
  { state: "NH", discipline: "electrical", code: "NEC 2023 with NH amendments", effective: "2025-07-01", org: "NH Division of Fire Safety", url: "https://www.firemarshal.dos.nh.gov/laws-rules-regulatory/state-fire-code/fire-codes-adopted-nh", quote: "NFPA 70, National Electrical Code (NEC) with NH Amendments", primary: true },
  { state: "NH", discipline: "fire", code: "NFPA 1 and NFPA 101, 2024 editions", effective: "2026-07-27", org: "NH Division of Fire Safety", url: "https://www.firemarshal.dos.nh.gov/laws-rules-regulatory/state-fire-code", quote: "Effective July 27, 2026, the State Fire Code was updated to the 2024 Edition of NFPA 1 and NFPA 101", primary: true },
  { state: "ME", discipline: "building", code: "MUBEC (2021 I-Codes)", effective: "2025-04-07", org: "Maine Bureau of Building Codes and Standards", url: "https://www.maine.gov/dps/fmo/sites/maine.gov.dps.fmo/files/inline-files/CodesPR043025.pdf", quote: "On Monday, April 7, 2025, updated building codes take effect in Maine", primary: true },
  { state: "ME", discipline: "electrical", code: "NEC 2023", effective: "2024-07-01", org: "Maine Electricians' Examining Board", url: "https://www.law.cornell.edu/regulations/maine/C-M-R-02-318-ch-120", quote: "must comply with the 2023 National Electrical Code as adopted by the Board", primary: false },
  { state: "ME", discipline: "fire", code: "NFPA 1, 2018 (Uniform Fire Code)", effective: "2019-11-27", org: "Maine Office of State Fire Marshal", url: "https://www11.maine.gov/dps/fmo/laws-rules-policy/rules", quote: "NFPA #1, Uniform Fire Code, 2018 edition", primary: true, note: "Older edition than peer states — confirm it has not been superseded." },
  { state: "VT", discipline: "building", code: "Vermont Fire & Building Safety Code 2025 (IBC 2021)", effective: null, org: "Vermont Division of Fire Safety", url: "https://firesafety.vermont.gov/sites/firesafety/files/Division%20Code%20Information%20Sheets/DFS%20Adopted%20Codes%20and%20Standards%20(3).pdf", quote: "IBC – 2021", primary: true, note: "The rule's own cover lists its effective date as TBD." },
  { state: "VT", discipline: "fire", code: "NFPA 1 and NFPA 101, 2021 editions", effective: null, org: "Vermont Division of Fire Safety", url: "https://firesafety.vermont.gov/sites/firesafety/files/Division%20Code%20Information%20Sheets/DFS%20Adopted%20Codes%20and%20Standards%20(3).pdf", quote: "NFPA 1 – 2021, NFPA 101 – 2021", primary: true, note: "The rule's own cover lists its effective date as TBD." },
  { state: "VT", discipline: "electrical", code: "NEC 2023 (Vermont Electrical Safety Rules 2025)", effective: "2025-11-05", org: "Vermont Division of Fire Safety", url: "https://firesafety.vermont.gov/sites/firesafety/files/Rules/2025%20Vermont%20Electrical%20Safety%20Rules.pdf", quote: "NFPA 70 ... 2023", primary: true },
  { state: "PA", discipline: "building", code: "Uniform Construction Code (2021 IBC)", effective: null, org: "PA Department of Labor & Industry", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/034/chapter403/s403.21.html", quote: "the 'International Building Code of 2021.'", primary: true, note: "2018 accessibility provisions remain in force after litigation." },
  { state: "PA", discipline: "electrical", code: null, effective: null, org: "PA Department of Labor & Industry", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/034/chapter403/s403.21.html", quote: "", primary: false, note: "Current NEC edition not confirmed from an official PA source." },
  { state: "PA", discipline: "fire", code: null, effective: null, org: "PA Department of Labor & Industry", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/034/chapter403/s403.21.html", quote: "", primary: false, note: "Current fire code edition not confirmed from an official PA source." },
  { state: "WA", discipline: "building", code: "2021 IBC (WAC 51-50)", effective: null, org: "Washington State Building Code Council", url: "https://apps.leg.wa.gov/wac/default.aspx?cite=51-50-003", quote: "The 2021 edition of the International Building Code, including Appendix E... is hereby adopted by reference.", primary: true, note: "2024 editions targeted for May 3, 2027." },
  { state: "WA", discipline: "electrical", code: "NEC 2023 (WAC 296-46B)", effective: "2024-04-01", org: "Washington Department of Labor & Industries", url: "https://lawfilesext.leg.wa.gov/law/wsr/2024/05/24-05-085.htm", quote: "adopts the 2023 edition of the National Fire Protection Agency (NFPA) 70... effective April 1, 2024", primary: true, note: "NEC 2026 adopted with a delayed effective date of December 31, 2026." },
  { state: "WA", discipline: "fire", code: "2021 IFC with WA amendments (WAC 51-54A)", effective: "2024-03-15", org: "Washington State Building Code Council", url: "https://sbcc.wa.gov/sites/default/files/2024-03/2021IFC_InsertPages2ndPrint_03012024.pdf", quote: "Washington State Amendments to the 2021 INTERNATIONAL FIRE CODE... Effective March 15, 2024", primary: true },
  { state: "CO", discipline: "building", code: null, effective: null, org: "Colorado Office of the State Architect", url: "https://osa.colorado.gov/building-codes", quote: "Colorado has no statewide building code; building codes are primarily adopted and enforced at the local level", primary: true },
  { state: "CO", discipline: "electrical", code: "NEC 2023 (3 CCR 710-1)", effective: "2023-08-01", org: "Colorado State Electrical Board", url: "https://www.law.cornell.edu/regulations/colorado/3-CCR-710-1.5", quote: "2023 Edition... The effective date shall be August 1, 2023.", primary: false, note: "A 2026 NEC rulemaking was pending." },
];

export const LOCAL_AMENDMENT_POLICY: LocalAmendmentPolicy[] = [
  { state: "FL", policy: "limited", text: "Local governments may adopt limited technical amendments to the Florida Building Code; they are published in local ordinances and filed with the Florida Building Commission. Local fire amendments are filed with the State Fire Marshal.", url: "https://www.myfloridacfo.com/division/sfm/bfp/florida-fire-prevention-code", primary: true },
  { state: "TX", policy: "local_codes_only", text: "Building and fire codes are adopted locally. Cities may amend the state electrical code.", url: "https://www.tdlr.texas.gov/ELECTRICIANS/compliance-guide.htm", primary: true },
  { state: "MD", policy: "permitted", text: "Each local jurisdiction may modify the building codes to suit local conditions, except the IECC and Maryland Accessibility Code.", url: "https://www.labor.maryland.gov/labor/build/buildcodes.shtml", primary: true },
  { state: "WA", policy: "permitted", text: "Cities and counties may amend within state minimums (RCW 19.27); amendments are in local municipal code.", url: "https://apps.leg.wa.gov/wac/default.aspx?cite=51-50-003", primary: true },
  { state: "CO", policy: "local_codes_only", text: "Building and fire codes and amendments are adopted by each county or municipality.", url: "https://osa.colorado.gov/building-codes", primary: true },
];

export const adoptionsFor = (state: string | null) => STATE_ADOPTIONS.filter((a) => a.state === state);
export const amendmentPolicyFor = (state: string | null) => LOCAL_AMENDMENT_POLICY.find((p) => p.state === state) ?? null;
