/**
 * Known code-adoption EVIDENCE (cache / baseline), researched 2026-09-30 from official sources.
 * These are evidence records, not answers: `resolveFamily()` decides what applies on the
 * Applicable Code Date. Historical editions are kept. New evidence discovered at runtime is
 * stored in `code_adoption_evidence` and merged with these records.
 * There is no "national amendments" layer — federal requirements are separate, not code amendments.
 */
import type { CodeEvidence } from "./codeTemporal";

export const RESEARCHED_AS_OF = "2026-09-30";
const R = RESEARCHED_AS_OF;
type Seed = Omit<CodeEvidence, "layer" | "retrieved_at"> & { retrieved_at?: string };
const ev = (x: Seed): CodeEvidence => ({ layer: "state", retrieved_at: R, ...x });

export const SEED_EVIDENCE: CodeEvidence[] = [
  // ── Texas: older current-code page vs newer adoption notice (temporal conflict fixture)
  ev({ state: "TX", family: "electrical", edition: "NEC 2023", effective_from: "2023-09-01", authority: "Texas Department of Licensing and Regulation", source_type: "agency_current_code_page", url: "https://www.tdlr.texas.gov/ELECTRICIANS/compliance-guide.htm", quote: "TDLR has adopted the National Electric Code 2023 Edition... It became effective September 1, 2023.", primary: true, note: "This page had not been updated for the 2026 adoption." }),
  ev({ state: "TX", family: "electrical", edition: "NEC 2023", effective_from: "2023-09-01", published: "2022-11-30", authority: "Texas Department of Licensing and Regulation", source_type: "adoption_notice", url: "https://www.tdlr.texas.gov/news/2022/11/30/2023-national-electrical-code-is-almost-here/", quote: "the proposed effective date will be September 1, 2023", primary: true }),
  ev({ state: "TX", family: "electrical", edition: "NEC 2026", adopted: "2026-07-28", effective_from: "2026-09-01", published: "2026-09-01", authority: "Texas Department of Licensing and Regulation", source_type: "adoption_notice", url: "https://www.tdlr.texas.gov/news/rulemaking/2026/09/01/commission-adopts-rules-12/", quote: "adopt the 2026 National Electrical Code as the state electrical code... effective date of September 1, 2026.", primary: true, note: "16 TAC §73.100; Texas Register 51 TexReg 5776." }),
  ev({ state: "TX", family: "building", edition: null, authority: "Texas Department of Licensing and Regulation", source_type: "informational", url: "https://www.tdlr.texas.gov/ELECTRICIANS/compliance-guide.htm", quote: "", primary: true, local_only: true, note: "Texas has no single statewide building code for most jurisdictions." }),
  ev({ state: "TX", family: "fire", edition: null, authority: "Texas Department of Licensing and Regulation", source_type: "informational", url: "https://www.tdlr.texas.gov/ELECTRICIANS/compliance-guide.htm", quote: "", primary: true, local_only: true }),

  // ── Florida: statute adopts "current edition" generically; the FBC-referenced year is from development material only
  ev({ state: "FL", family: "electrical", edition: "NEC 2023", authority: "Florida Building Commission", source_type: "development", url: "https://www.floridabuilding.org/fbc/thecode/2026_Code_Development/Pre_December_2025_FBC/Electrical_detail.pdf", quote: "adoption of NFPA 70-23, including all published TIAs", primary: true, proposed: true, note: "Code-development record for the next FBC — not an adoption." }),
  ev({ state: "FL", family: "electrical", edition: null, authority: "Florida Statutes §553.88", source_type: "statute", url: "https://www.flsenate.gov/Laws/Statutes/2024/0553.88", quote: "the current edition of the following standards are adopted: (1) 'National Electrical Code,' NFPA No. 70.", primary: true, note: "Adopts NFPA 70 without naming an edition year; the FBC 8th Edition Chapter 35 reference must be read to confirm the year." }),
  ev({ state: "FL", family: "fire", edition: "FFPC 8th Edition (2023)", effective_from: "2023-12-31", authority: "Florida Division of State Fire Marshal", source_type: "agency_current_code_page", url: "https://www.myfloridacfo.com/division/sfm/bfp/florida-fire-prevention-code", quote: "8th Edition (2023) FFPC Online & Purchasing (Effective date: December 31, 2023)", primary: true }),
  ev({ state: "FL", family: "building", edition: "FBC 8th Edition (2023)", effective_from: "2023-12-31", authority: "Florida Building Commission", source_type: "agency_current_code_page", url: "https://www.floridabuilding.org/c/default.aspx", quote: "Florida Building Code, 8th Edition (2023), is December 31, 2023", primary: true }),
  ev({ state: "FL", family: "building", edition: "FBC 9th Edition (2026)", authority: "Florida Building Commission", source_type: "development", url: "https://www.floridabuilding.org/c/default.aspx", quote: "9th Edition (2026)", primary: true, proposed: true }),

  // ── Maryland
  ev({ state: "MD", family: "building", edition: "2021 IBC/IRC/IECC (MBPS)", effective_from: "2023-05-29", authority: "Maryland Department of Labor", source_type: "agency_current_code_page", url: "https://www.labor.maryland.gov/labor/build/buildcodes.shtml", quote: "2021 International Building Code... 2021 International Residential Code... 2021 International Energy Conservation Code", primary: true, note: "Effective date from a secondary timeline." }),
  ev({ state: "MD", family: "electrical", edition: null, authority: "Maryland Department of Labor", source_type: "agency_current_code_page", url: "https://www.labor.maryland.gov/labor/build/buildcodematrix.pdf", quote: "Electrical (3) local jurisdiction (locally adopted)", primary: true, local_only: true }),
  ev({ state: "MD", family: "fire", edition: "NFPA 1 / NFPA 101 (2024)", authority: "Maryland Department of Labor (code matrix)", source_type: "agency_current_code_page", url: "https://www.labor.maryland.gov/labor/build/buildcodematrix.pdf", quote: "not applicable to one- and two-family dwellings and buildings located in Baltimore City", primary: true, note: "Not applicable to one- and two-family dwellings or Baltimore City." }),

  // ── DC
  ev({ state: "DC", family: "building", edition: "2017 DC Construction Codes (2015 ICC)", effective_from: "2020-05-29", authority: "DC Department of Buildings", source_type: "agency_current_code_page", url: "https://dob.dc.gov/node/1615636", quote: "The 2017 DC Construction Code takes effect on May 29, 2020.", primary: true }),
  ev({ state: "DC", family: "electrical", edition: "NEC 2014 (as amended)", effective_from: "2020-05-29", authority: "DC Department of Buildings", source_type: "official_publication", url: "https://up.codes/viewer/district-of-columbia/ibc-2015/chapter/new_1/administration-and-enforcement", quote: "The National Electrical Code (2014) published by the National Fire Protection Association", primary: false }),
  ev({ state: "DC", family: "fire", edition: "2015 IFC (DC Fire Code 2017)", effective_from: "2020-05-29", authority: "DC Department of Buildings", source_type: "official_publication", url: "https://up.codes/viewer/district-of-columbia/ifc-2015/chapter/1/scope-and-enforcement", quote: "shall consist of the 2015 edition of the International Fire Code as amended", primary: false }),

  // ── Virginia
  ev({ state: "VA", family: "building", edition: "2021 Virginia USBC", effective_from: "2024-01-18", authority: "Virginia DHCD", source_type: "agency_current_code_page", url: "https://www.dhcd.virginia.gov/node/582", quote: "The effective date of the 2021 Uniform Statewide Building Code... is Jan. 18, 2024.", primary: true }),
  ev({ state: "VA", family: "electrical", edition: "NEC 2020", effective_from: "2024-01-18", authority: "Virginia DHCD", source_type: "agency_current_code_page", url: "https://www.dhcd.virginia.gov/node/582", quote: "Virginia adopted the 2021 I-codes... and the 2020 National Electrical Code.", primary: true }),
  ev({ state: "VA", family: "fire", edition: "2021 Virginia SFPC", effective_from: "2024-01-18", authority: "Virginia DHCD (copy published by Fluvanna County)", source_type: "official_publication", url: "https://www.fluvannacounty.org/sites/default/files/fileattachments/building_inspections/page/511/2021-virginia-statewide-fire-prevention-code.pdf", quote: "Effective Date: January 18, 2024", primary: false }),

  // ── North Carolina: 2024 package adopted but effective date delayed indefinitely (S.L. 2025-2)
  ev({ state: "NC", family: "building", edition: "2018 NC State Building Code", effective_from: "2019-01-01", authority: "NC Office of State Fire Marshal", source_type: "official_publication", url: "https://www.ncbarch.org/wp-content/uploads/2025/01/2024-1212-Effective-date-of-the-2024-North-Carolina-State-Building-Code.pdf", quote: "the 2018 North Carolina State Building Code remains effective", primary: false }),
  ev({ state: "NC", family: "building", edition: "2024 NC State Building Code", adopted: "2022-09-12", authority: "NC Office of State Fire Marshal", source_type: "guidance", url: "https://www.ncosfm.gov/news/press-releases/2025/04/07/north-carolina-delays-implementation-2024-state-building-code", quote: "the effective date of the 2024 Code to 12 months after the State Fire Marshal certifies that two key conditions have been met", primary: true, proposed: true, note: "Adopted, but its effective date is not yet fixed (S.L. 2025-2)." }),
  ev({ state: "NC", family: "electrical", edition: "2023 NC Electrical Code (NEC 2023)", authority: "NC Office of State Fire Marshal", source_type: "official_publication", url: "https://www.ncbarch.org/wp-content/uploads/2025/01/2024-1212-Effective-date-of-the-2024-North-Carolina-State-Building-Code.pdf", quote: "2023 North Carolina Electrical Code (2023 NFPA 70 National Electrical Code with NC Amendments)", primary: false, proposed: true, note: "Part of the delayed 2024 package." }),
  ev({ state: "NC", family: "fire", edition: "2024 NC Fire Code", adopted: "2022-09-12", authority: "NC Office of Administrative Hearings", source_type: "official_publication", url: "https://www.oah.nc.gov/2024-ncfire-code-amendments-final/open", quote: "adopted by the North Carolina Building Code Council on September 12, 2022 to be effective January 1, 2025", primary: true, proposed: true, note: "Apparently delayed with the 2024 package — not confirmed." }),

  // ── Massachusetts
  ev({ state: "MA", family: "building", edition: "780 CMR 10th Edition (2021 I-Codes)", effective_from: "2024-10-11", authority: "Massachusetts BBRS", source_type: "adoption_notice", url: "https://www.mass.gov/news/10th-edition-of-the-state-building-code-board-of-building-regulations-and-standards", quote: "Effective October 11, 2024, the 10th Edition of the State Building Code will take effect.", primary: true }),
  ev({ state: "MA", family: "electrical", edition: "NEC 2020 (527 CMR 12.00)", effective_from: "2020-01-01", authority: "527 CMR 12.00 (LII mirror)", source_type: "official_publication", url: "https://www.law.cornell.edu/regulations/massachusetts/department-527-CMR/title-527-CMR-12.00", quote: "shall be the 2020 National Electrical Code (NEC)", primary: false, note: "Stale mirror; exact 2020 start date approximate." }),
  ev({ state: "MA", family: "electrical", edition: "NEC 2023 (527 CMR 12.00)", effective_from: "2023-02-17", authority: "Massachusetts Board of Fire Prevention Regulations", source_type: "agency_current_code_page", url: "https://www.mass.gov/info-details/massachusetts-electrical-code", quote: "Prior edition 2023 NEC effective February 17, 2023", primary: true }),
  ev({ state: "MA", family: "electrical", edition: "NEC 2026 (527 CMR 12.00)", effective_from: "2026-04-24", authority: "Massachusetts Board of Fire Prevention Regulations", source_type: "rule", url: "https://www.mass.gov/doc/527-cmr-1200-massachusetts-electrical-code-effective-42426/download", quote: "shall be the 2026 National Electrical Code (NEC)... in the form released by vote of the NFPA Standards Council on August 20, 2025", primary: true }),
  ev({ state: "MA", family: "fire", edition: "527 CMR 1.00 (NFPA 1, 2021)", effective_from: "2022-12-09", authority: "Massachusetts Department of Fire Services", source_type: "agency_current_code_page", url: "https://www.mass.gov/info-details/massachusetts-fire-code", quote: "The current State Fire Code went into effect on December 9, 2022.", primary: true }),

  // ── New Hampshire
  ev({ state: "NH", family: "fire", edition: "NFPA 1 / NFPA 101 (2021)", effective_from: "2025-07-01", authority: "NH Division of Fire Safety", source_type: "agency_current_code_page", url: "https://www.firemarshal.dos.nh.gov/laws-rules-regulatory/state-fire-code/fire-codes-adopted-nh", quote: "2021 NFPA 101, Life Safety Code... 2021 NFPA 1, Fire Code... Effective date: July 1, 2025", primary: true, note: "List page not yet updated for the 2024 editions." }),
  ev({ state: "NH", family: "fire", edition: "NFPA 1 / NFPA 101 (2024)", effective_from: "2026-07-27", authority: "NH Division of Fire Safety", source_type: "adoption_notice", url: "https://www.firemarshal.dos.nh.gov/laws-rules-regulatory/state-fire-code", quote: "Effective July 27, 2026, the State Fire Code was updated to the 2024 Edition of NFPA 1 and NFPA 101", primary: true, note: "Under RSA 153:1 as ratified; statute text not read directly." }),
  ev({ state: "NH", family: "electrical", edition: "NEC 2023 (NH amendments)", effective_from: "2025-07-01", authority: "NH Division of Fire Safety", source_type: "agency_current_code_page", url: "https://www.firemarshal.dos.nh.gov/laws-rules-regulatory/state-fire-code/fire-codes-adopted-nh", quote: "2023 NFPA 70, National Electrical Code (NEC) with NH Amendments", primary: true }),
  ev({ state: "NH", family: "building", edition: "2021 I-Codes (RSA 155-A, HB 1059)", effective_from: "2024-07-01", authority: "City of Portsmouth (citing state law)", source_type: "guidance", url: "https://www.portsmouthnh.gov/inspection/news/nh-building-code-and-fire-code-updates", quote: "updated the NH State Building Code (RSA 155-A) to the 2021 editions with NH amendments... went into effect July 1, 2024", primary: false }),
  ev({ state: "NH", family: "building", edition: "2024 I-Codes (IECC 2018)", effective_from: "2026-07-01", authority: "NH State Building Code Review Board (copy published by Town of Merrimack)", source_type: "official_publication", url: "https://www.merrimacknh.gov/DocumentCenter/View/5723/2024-NH-State-Building-Code", quote: "updating six of the adopted model codes to the 2024 edition, excluding the 2018 IECC and the 2023 NEC", primary: false }),

  // ── Maine
  ev({ state: "ME", family: "building", edition: "MUBEC (2021 I-Codes)", effective_from: "2025-04-07", authority: "Maine Bureau of Building Codes and Standards", source_type: "adoption_notice", url: "https://www.maine.gov/dps/fmo/sites/maine.gov.dps.fmo/files/inline-files/CodesPR043025.pdf", quote: "On Monday, April 7, 2025, updated building codes take effect in Maine", primary: true }),
  ev({ state: "ME", family: "electrical", edition: "NEC 2023", effective_from: "2024-07-01", authority: "Maine Electricians' Examining Board (LII mirror)", source_type: "rule", url: "https://www.law.cornell.edu/regulations/maine/C-M-R-02-318-ch-120", quote: "must comply with the 2023 National Electrical Code as adopted by the Board", primary: false }),
  ev({ state: "ME", family: "fire", edition: "NFPA 1 (2018)", authority: "Maine Office of State Fire Marshal", source_type: "agency_current_code_page", url: "https://www.maine.gov/dps/fmo/laws-rules-policy/rules", quote: "Chapter 3: Fire Prevention Code - amended 11/27/2019 - NFPA #1, Uniform Fire Code, 2018 edition", primary: true, note: "A third-party tracker suggests a July 28, 2026 transition that could not be confirmed." }),
  ev({ state: "ME", family: "fire", edition: "Newer NFPA 1 edition (unconfirmed)", authority: "UpCodes (third-party)", source_type: "informational", url: "https://up.codes/viewer/maine/nfpa-1-2018", quote: "Adoption timeline Effective Jul 28, 2026", primary: false }),

  // ── Vermont
  ev({ state: "VT", family: "building", edition: "VFBSC 2025 (IBC 2021)", adopted: "2025-11-04", authority: "Vermont Division of Fire Safety", source_type: "rule", url: "https://firesafety.vermont.gov/sites/firesafety/files/Rules/VFBSC%202025%20Rules%20Annotated.pdf", quote: "EFFECTIVE DATE: TBD", primary: true, note: "Adopted November 4, 2025; effective date not fixed in the rule." }),
  ev({ state: "VT", family: "fire", edition: "NFPA 1 / NFPA 101 (2021)", adopted: "2025-11-04", authority: "Vermont Division of Fire Safety", source_type: "agency_current_code_page", url: "https://firesafety.vermont.gov/sites/firesafety/files/Division%20Code%20Information%20Sheets/DFS%20Adopted%20Codes%20and%20Standards%20(3).pdf", quote: "NFPA 1 – 2021, NFPA 101 – 2021", primary: true }),
  ev({ state: "VT", family: "electrical", edition: "NEC 2023", effective_from: "2025-11-05", authority: "Vermont Division of Fire Safety", source_type: "rule", url: "https://firesafety.vermont.gov/sites/firesafety/files/Rules/2025%20Vermont%20Electrical%20Safety%20Rules.pdf", quote: "NFPA 70 ... 2023", primary: true }),

  // ── Pennsylvania: official register vs stale mirror
  ev({ state: "PA", family: "building", edition: "UCC — IBC 2018", authority: "34 Pa. Code §403.21 (LII mirror)", source_type: "official_publication", url: "https://www.law.cornell.edu/regulations/pennsylvania/34-Pa-Code-SS-403-21", quote: "International Building Code of 2018", primary: false }),
  ev({ state: "PA", family: "building", edition: "UCC — IBC 2021", authority: "PA Department of Labor & Industry (Pa. Code & Bulletin)", source_type: "rule", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/034/chapter403/s403.21.html", quote: "the 'International Building Code of 2021.'", primary: true, note: "Effective date not established; 2018 accessibility provisions remain after litigation." }),

  // ── Washington
  ev({ state: "WA", family: "building", edition: "2021 IBC (WAC 51-50)", effective_from: "2024-03-15", authority: "Washington State Building Code Council", source_type: "rule", url: "https://apps.leg.wa.gov/wac/default.aspx?cite=51-50-003", quote: "The 2021 edition of the International Building Code, including Appendix E... is hereby adopted by reference.", primary: true, note: "Effective date aligned with the 2021 WA code cycle." }),
  ev({ state: "WA", family: "building", edition: "2024 IBC", effective_from: "2027-05-03", authority: "Washington State Building Code Council", source_type: "development", url: "https://sbcc.wa.gov/", quote: "The effective date of the 2024 codes will be May 3, 2027.", primary: true, proposed: true, note: "Final adoption targeted for October 16, 2026." }),
  ev({ state: "WA", family: "electrical", edition: "NEC 2023", effective_from: "2024-04-01", authority: "Washington Department of Labor & Industries", source_type: "rule", url: "https://lawfilesext.leg.wa.gov/law/wsr/2024/05/24-05-085.htm", quote: "adopts the 2023 edition of the National Fire Protection Agency (NFPA) 70... effective April 1, 2024", primary: true }),
  ev({ state: "WA", family: "electrical", edition: "NEC 2026", effective_from: "2026-12-31", adopted: "2025-11-18", authority: "Washington Department of Labor & Industries", source_type: "rule", url: "https://apps.leg.wa.gov/wAc/default.aspx?cite=296-46B-010", quote: "Effective December 31, 2026, the 2026 edition of the National Electrical Code (NFPA 70-2026)... replaces the 2023 edition", primary: true }),
  ev({ state: "WA", family: "fire", edition: "2021 IFC (WAC 51-54A)", effective_from: "2024-03-15", authority: "Washington State Building Code Council", source_type: "official_publication", url: "https://sbcc.wa.gov/sites/default/files/2024-03/2021IFC_InsertPages2ndPrint_03012024.pdf", quote: "Washington State Amendments to the 2021 INTERNATIONAL FIRE CODE... Effective March 15, 2024", primary: true }),

  // ── Colorado: local adoption; statewide NEC
  ev({ state: "CO", family: "building", edition: null, authority: "Colorado Office of the State Architect", source_type: "agency_current_code_page", url: "https://osa.colorado.gov/building-codes", quote: "Colorado has no statewide building code; building codes are primarily adopted and enforced at the local level", primary: true, local_only: true }),
  ev({ state: "CO", family: "fire", edition: null, authority: "Colorado Office of the State Architect", source_type: "agency_current_code_page", url: "https://osa.colorado.gov/building-codes", quote: "Colorado has no statewide building code", primary: true, local_only: true }),
  ev({ state: "CO", family: "electrical", edition: "NEC 2023", effective_from: "2023-08-01", authority: "Colorado State Electrical Board (LII mirror)", source_type: "rule", url: "https://www.law.cornell.edu/regulations/colorado/3-CCR-710-1.5", quote: "2023 Edition... The effective date shall be August 1, 2023.", primary: false }),
  ev({ state: "CO", family: "electrical", edition: "NEC 2026", effective_from: "2026-08-01", authority: "Colorado Office of the State Architect (citing State Electrical Board)", source_type: "agency_current_code_page", url: "https://osa.colorado.gov/sites/osa/files/documents/Exh-A-BldgCodes%202026%20R1.pdf", quote: "The 2026 edition of the National Electrical Code (NEC) (NFPA 70®) (As adopted by the Colorado State Electrical Board Effective August 1, 2026)", primary: true }),
];

export type LocalAmendmentPolicy = { state: string; policy: "permitted" | "limited" | "not_permitted" | "local_codes_only" | "unknown"; text: string; url: string };
export const LOCAL_AMENDMENT_POLICY: LocalAmendmentPolicy[] = [
  { state: "FL", policy: "limited", text: "Local governments may adopt limited technical amendments to the Florida Building Code; local fire amendments are filed with the State Fire Marshal.", url: "https://www.myfloridacfo.com/division/sfm/bfp/florida-fire-prevention-code" },
  { state: "TX", policy: "local_codes_only", text: "Building and fire codes are adopted by each city or county — the state baseline is only the electrical code.", url: "https://www.tdlr.texas.gov/ELECTRICIANS/compliance-guide.htm" },
  { state: "MD", policy: "permitted", text: "Each local jurisdiction may modify the building codes, except the IECC and Maryland Accessibility Code. Electrical is locally adopted.", url: "https://www.labor.maryland.gov/labor/build/buildcodes.shtml" },
  { state: "WA", policy: "permitted", text: "Cities and counties may amend within state minimums (RCW 19.27).", url: "https://apps.leg.wa.gov/wac/default.aspx?cite=51-50-003" },
  { state: "CO", policy: "local_codes_only", text: "Building and fire codes are adopted by each county or municipality; the state baseline is only the electrical code.", url: "https://osa.colorado.gov/building-codes" },
];

/** States where the local adoption, not the state baseline, determines the applicable building code. */
export const LOCAL_ADOPTION_STATES = LOCAL_AMENDMENT_POLICY.filter((p) => p.policy === "local_codes_only" || p.policy === "permitted").map((p) => p.state);
export const seedFor = (state: string | null) => SEED_EVIDENCE.filter((e) => e.state === state);
export const amendmentPolicyFor = (state: string | null) => LOCAL_AMENDMENT_POLICY.find((p) => p.state === state) ?? null;
