/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedLookupRouteImport } from './routes/_authenticated/lookup'
import { Route as AuthenticatedJurisdictionsRouteImport } from './routes/_authenticated/jurisdictions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as ShareReportsTokenRouteImport } from './routes/share.reports.$token'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat.stream'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedJurisdictionsSlugRouteImport } from './routes/_authenticated/jurisdictions.$slug'
import { Route as AuthenticatedInspectionsIdRouteImport } from './routes/_authenticated/inspections.$id'
import { Route as AuthenticatedAssistantAnalysisRouteImport } from './routes/_authenticated/assistant.analysis'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated/assistant.$threadId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLookupRoute = AuthenticatedLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJurisdictionsRoute =
  AuthenticatedJurisdictionsRouteImport.update({
    id: '/jurisdictions',
    path: '/jurisdictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const ShareReportsTokenRoute = ShareReportsTokenRouteImport.update({
  id: '/share/reports/$token',
  path: '/share/reports/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJurisdictionsSlugRoute =
  AuthenticatedJurisdictionsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedJurisdictionsRoute,
  } as any)
const AuthenticatedInspectionsIdRoute =
  AuthenticatedInspectionsIdRouteImport.update({
    id: '/inspections/$id',
    path: '/inspections/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantAnalysisRoute =
  AuthenticatedAssistantAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jurisdictions': typeof AuthenticatedJurisdictionsRouteWithChildren
  '/lookup': typeof AuthenticatedLookupRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/assistant/analysis': typeof AuthenticatedAssistantAnalysisRoute
  '/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/jurisdictions/$slug': typeof AuthenticatedJurisdictionsSlugRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/share/reports/$token': typeof ShareReportsTokenRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jurisdictions': typeof AuthenticatedJurisdictionsRouteWithChildren
  '/lookup': typeof AuthenticatedLookupRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/assistant/analysis': typeof AuthenticatedAssistantAnalysisRoute
  '/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/jurisdictions/$slug': typeof AuthenticatedJurisdictionsSlugRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/share/reports/$token': typeof ShareReportsTokenRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jurisdictions': typeof AuthenticatedJurisdictionsRouteWithChildren
  '/_authenticated/lookup': typeof AuthenticatedLookupRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/assistant/analysis': typeof AuthenticatedAssistantAnalysisRoute
  '/_authenticated/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/_authenticated/jurisdictions/$slug': typeof AuthenticatedJurisdictionsSlugRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/share/reports/$token': typeof ShareReportsTokenRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/assistant'
    | '/dashboard'
    | '/jurisdictions'
    | '/lookup'
    | '/checkout/return'
    | '/assistant/$threadId'
    | '/assistant/analysis'
    | '/inspections/$id'
    | '/jurisdictions/$slug'
    | '/projects/$id'
    | '/api/chat/stream'
    | '/share/reports/$token'
    | '/assistant/'
    | '/projects/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/dashboard'
    | '/jurisdictions'
    | '/lookup'
    | '/checkout/return'
    | '/assistant/$threadId'
    | '/assistant/analysis'
    | '/inspections/$id'
    | '/jurisdictions/$slug'
    | '/projects/$id'
    | '/api/chat/stream'
    | '/share/reports/$token'
    | '/assistant'
    | '/projects'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/jurisdictions'
    | '/_authenticated/lookup'
    | '/checkout/return'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/assistant/analysis'
    | '/_authenticated/inspections/$id'
    | '/_authenticated/jurisdictions/$slug'
    | '/_authenticated/projects/$id'
    | '/api/chat/stream'
    | '/share/reports/$token'
    | '/_authenticated/assistant/'
    | '/_authenticated/projects/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ShareReportsTokenRoute: typeof ShareReportsTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lookup': {
      id: '/_authenticated/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof AuthenticatedLookupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurisdictions': {
      id: '/_authenticated/jurisdictions'
      path: '/jurisdictions'
      fullPath: '/jurisdictions'
      preLoaderRoute: typeof AuthenticatedJurisdictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/share/reports/$token': {
      id: '/share/reports/$token'
      path: '/share/reports/$token'
      fullPath: '/share/reports/$token'
      preLoaderRoute: typeof ShareReportsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurisdictions/$slug': {
      id: '/_authenticated/jurisdictions/$slug'
      path: '/$slug'
      fullPath: '/jurisdictions/$slug'
      preLoaderRoute: typeof AuthenticatedJurisdictionsSlugRouteImport
      parentRoute: typeof AuthenticatedJurisdictionsRoute
    }
    '/_authenticated/inspections/$id': {
      id: '/_authenticated/inspections/$id'
      path: '/inspections/$id'
      fullPath: '/inspections/$id'
      preLoaderRoute: typeof AuthenticatedInspectionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/analysis': {
      id: '/_authenticated/assistant/analysis'
      path: '/analysis'
      fullPath: '/assistant/analysis'
      preLoaderRoute: typeof AuthenticatedAssistantAnalysisRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAssistantRouteChildren {
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedAssistantAnalysisRoute: typeof AuthenticatedAssistantAnalysisRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
}

const AuthenticatedAssistantRouteChildren: AuthenticatedAssistantRouteChildren =
  {
    AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
    AuthenticatedAssistantAnalysisRoute: AuthenticatedAssistantAnalysisRoute,
    AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  }

const AuthenticatedAssistantRouteWithChildren =
  AuthenticatedAssistantRoute._addFileChildren(
    AuthenticatedAssistantRouteChildren,
  )

interface AuthenticatedJurisdictionsRouteChildren {
  AuthenticatedJurisdictionsSlugRoute: typeof AuthenticatedJurisdictionsSlugRoute
}

const AuthenticatedJurisdictionsRouteChildren: AuthenticatedJurisdictionsRouteChildren =
  {
    AuthenticatedJurisdictionsSlugRoute: AuthenticatedJurisdictionsSlugRoute,
  }

const AuthenticatedJurisdictionsRouteWithChildren =
  AuthenticatedJurisdictionsRoute._addFileChildren(
    AuthenticatedJurisdictionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJurisdictionsRoute: typeof AuthenticatedJurisdictionsRouteWithChildren
  AuthenticatedLookupRoute: typeof AuthenticatedLookupRoute
  AuthenticatedInspectionsIdRoute: typeof AuthenticatedInspectionsIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJurisdictionsRoute: AuthenticatedJurisdictionsRouteWithChildren,
  AuthenticatedLookupRoute: AuthenticatedLookupRoute,
  AuthenticatedInspectionsIdRoute: AuthenticatedInspectionsIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ShareReportsTokenRoute: ShareReportsTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
