/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedPropertyRouteImport } from './routes/_authenticated/property'
import { Route as AuthenticatedPortalsRouteImport } from './routes/_authenticated/portals'
import { Route as AuthenticatedLookupRouteImport } from './routes/_authenticated/lookup'
import { Route as AuthenticatedJurisdictionsRouteImport } from './routes/_authenticated/jurisdictions'
import { Route as AuthenticatedHealthPortalsRouteImport } from './routes/_authenticated/health-portals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as ShareReportsTokenRouteImport } from './routes/share.reports.$token'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat.stream'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedJurisdictionsSlugRouteImport } from './routes/_authenticated/jurisdictions.$slug'
import { Route as AuthenticatedInspectionsIdRouteImport } from './routes/_authenticated/inspections.$id'
import { Route as AuthenticatedAssistantScreensRouteImport } from './routes/_authenticated/assistant.screens'
import { Route as AuthenticatedAssistantAnalysisRouteImport } from './routes/_authenticated/assistant.analysis'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated/assistant.$threadId'
import { Route as AuthenticatedAdminPortalsRouteImport } from './routes/_authenticated/admin.portals'
import { Route as AuthenticatedAdminHealthPortalsRouteImport } from './routes/_authenticated/admin.health-portals'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAssistantScreensIndexRouteImport } from './routes/_authenticated/assistant.screens.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksRefreshLinkedPermitsRouteImport } from './routes/api/public/hooks/refresh-linked-permits'
import { Route as AuthenticatedAssistantScreensIdRouteImport } from './routes/_authenticated/assistant.screens.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertyRoute = AuthenticatedPropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalsRoute = AuthenticatedPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLookupRoute = AuthenticatedLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJurisdictionsRoute =
  AuthenticatedJurisdictionsRouteImport.update({
    id: '/jurisdictions',
    path: '/jurisdictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthPortalsRoute =
  AuthenticatedHealthPortalsRouteImport.update({
    id: '/health-portals',
    path: '/health-portals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const ShareReportsTokenRoute = ShareReportsTokenRouteImport.update({
  id: '/share/reports/$token',
  path: '/share/reports/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJurisdictionsSlugRoute =
  AuthenticatedJurisdictionsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedJurisdictionsRoute,
  } as any)
const AuthenticatedInspectionsIdRoute =
  AuthenticatedInspectionsIdRouteImport.update({
    id: '/inspections/$id',
    path: '/inspections/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantScreensRoute =
  AuthenticatedAssistantScreensRouteImport.update({
    id: '/screens',
    path: '/screens',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const AuthenticatedAssistantAnalysisRoute =
  AuthenticatedAssistantAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const AuthenticatedAdminPortalsRoute =
  AuthenticatedAdminPortalsRouteImport.update({
    id: '/admin/portals',
    path: '/admin/portals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHealthPortalsRoute =
  AuthenticatedAdminHealthPortalsRouteImport.update({
    id: '/admin/health-portals',
    path: '/admin/health-portals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantScreensIndexRoute =
  AuthenticatedAssistantScreensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistantScreensRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshLinkedPermitsRoute =
  ApiPublicHooksRefreshLinkedPermitsRouteImport.update({
    id: '/api/public/hooks/refresh-linked-permits',
    path: '/api/public/hooks/refresh-linked-permits',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAssistantScreensIdRoute =
  AuthenticatedAssistantScreensIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAssistantScreensRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health-portals': typeof AuthenticatedHealthPortalsRoute
  '/jurisdictions': typeof AuthenticatedJurisdictionsRouteWithChildren
  '/lookup': typeof AuthenticatedLookupRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/property': typeof AuthenticatedPropertyRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/health-portals': typeof AuthenticatedAdminHealthPortalsRoute
  '/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/assistant/analysis': typeof AuthenticatedAssistantAnalysisRoute
  '/assistant/screens': typeof AuthenticatedAssistantScreensRouteWithChildren
  '/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/jurisdictions/$slug': typeof AuthenticatedJurisdictionsSlugRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/share/reports/$token': typeof ShareReportsTokenRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/assistant/screens/$id': typeof AuthenticatedAssistantScreensIdRoute
  '/api/public/hooks/refresh-linked-permits': typeof ApiPublicHooksRefreshLinkedPermitsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/assistant/screens/': typeof AuthenticatedAssistantScreensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health-portals': typeof AuthenticatedHealthPortalsRoute
  '/jurisdictions': typeof AuthenticatedJurisdictionsRouteWithChildren
  '/lookup': typeof AuthenticatedLookupRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/property': typeof AuthenticatedPropertyRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/health-portals': typeof AuthenticatedAdminHealthPortalsRoute
  '/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/assistant/analysis': typeof AuthenticatedAssistantAnalysisRoute
  '/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/jurisdictions/$slug': typeof AuthenticatedJurisdictionsSlugRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/share/reports/$token': typeof ShareReportsTokenRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/assistant/screens/$id': typeof AuthenticatedAssistantScreensIdRoute
  '/api/public/hooks/refresh-linked-permits': typeof ApiPublicHooksRefreshLinkedPermitsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/assistant/screens': typeof AuthenticatedAssistantScreensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/health-portals': typeof AuthenticatedHealthPortalsRoute
  '/_authenticated/jurisdictions': typeof AuthenticatedJurisdictionsRouteWithChildren
  '/_authenticated/lookup': typeof AuthenticatedLookupRoute
  '/_authenticated/portals': typeof AuthenticatedPortalsRoute
  '/_authenticated/property': typeof AuthenticatedPropertyRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/health-portals': typeof AuthenticatedAdminHealthPortalsRoute
  '/_authenticated/admin/portals': typeof AuthenticatedAdminPortalsRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/assistant/analysis': typeof AuthenticatedAssistantAnalysisRoute
  '/_authenticated/assistant/screens': typeof AuthenticatedAssistantScreensRouteWithChildren
  '/_authenticated/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/_authenticated/jurisdictions/$slug': typeof AuthenticatedJurisdictionsSlugRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/share/reports/$token': typeof ShareReportsTokenRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/assistant/screens/$id': typeof AuthenticatedAssistantScreensIdRoute
  '/api/public/hooks/refresh-linked-permits': typeof ApiPublicHooksRefreshLinkedPermitsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/assistant/screens/': typeof AuthenticatedAssistantScreensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pricing'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assistant'
    | '/dashboard'
    | '/health-portals'
    | '/jurisdictions'
    | '/lookup'
    | '/portals'
    | '/property'
    | '/checkout/return'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/health-portals'
    | '/admin/portals'
    | '/assistant/$threadId'
    | '/assistant/analysis'
    | '/assistant/screens'
    | '/inspections/$id'
    | '/jurisdictions/$slug'
    | '/projects/$id'
    | '/api/chat/stream'
    | '/share/reports/$token'
    | '/assistant/'
    | '/projects/'
    | '/assistant/screens/$id'
    | '/api/public/hooks/refresh-linked-permits'
    | '/api/public/payments/webhook'
    | '/assistant/screens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pricing'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/health-portals'
    | '/jurisdictions'
    | '/lookup'
    | '/portals'
    | '/property'
    | '/checkout/return'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/health-portals'
    | '/admin/portals'
    | '/assistant/$threadId'
    | '/assistant/analysis'
    | '/inspections/$id'
    | '/jurisdictions/$slug'
    | '/projects/$id'
    | '/api/chat/stream'
    | '/share/reports/$token'
    | '/assistant'
    | '/projects'
    | '/assistant/screens/$id'
    | '/api/public/hooks/refresh-linked-permits'
    | '/api/public/payments/webhook'
    | '/assistant/screens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/pricing'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/health-portals'
    | '/_authenticated/jurisdictions'
    | '/_authenticated/lookup'
    | '/_authenticated/portals'
    | '/_authenticated/property'
    | '/checkout/return'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/health-portals'
    | '/_authenticated/admin/portals'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/assistant/analysis'
    | '/_authenticated/assistant/screens'
    | '/_authenticated/inspections/$id'
    | '/_authenticated/jurisdictions/$slug'
    | '/_authenticated/projects/$id'
    | '/api/chat/stream'
    | '/share/reports/$token'
    | '/_authenticated/assistant/'
    | '/_authenticated/projects/'
    | '/_authenticated/assistant/screens/$id'
    | '/api/public/hooks/refresh-linked-permits'
    | '/api/public/payments/webhook'
    | '/_authenticated/assistant/screens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ShareReportsTokenRoute: typeof ShareReportsTokenRoute
  ApiPublicHooksRefreshLinkedPermitsRoute: typeof ApiPublicHooksRefreshLinkedPermitsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/property': {
      id: '/_authenticated/property'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof AuthenticatedPropertyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portals': {
      id: '/_authenticated/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof AuthenticatedPortalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lookup': {
      id: '/_authenticated/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof AuthenticatedLookupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurisdictions': {
      id: '/_authenticated/jurisdictions'
      path: '/jurisdictions'
      fullPath: '/jurisdictions'
      preLoaderRoute: typeof AuthenticatedJurisdictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health-portals': {
      id: '/_authenticated/health-portals'
      path: '/health-portals'
      fullPath: '/health-portals'
      preLoaderRoute: typeof AuthenticatedHealthPortalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/share/reports/$token': {
      id: '/share/reports/$token'
      path: '/share/reports/$token'
      fullPath: '/share/reports/$token'
      preLoaderRoute: typeof ShareReportsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurisdictions/$slug': {
      id: '/_authenticated/jurisdictions/$slug'
      path: '/$slug'
      fullPath: '/jurisdictions/$slug'
      preLoaderRoute: typeof AuthenticatedJurisdictionsSlugRouteImport
      parentRoute: typeof AuthenticatedJurisdictionsRoute
    }
    '/_authenticated/inspections/$id': {
      id: '/_authenticated/inspections/$id'
      path: '/inspections/$id'
      fullPath: '/inspections/$id'
      preLoaderRoute: typeof AuthenticatedInspectionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/screens': {
      id: '/_authenticated/assistant/screens'
      path: '/screens'
      fullPath: '/assistant/screens'
      preLoaderRoute: typeof AuthenticatedAssistantScreensRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/_authenticated/assistant/analysis': {
      id: '/_authenticated/assistant/analysis'
      path: '/analysis'
      fullPath: '/assistant/analysis'
      preLoaderRoute: typeof AuthenticatedAssistantAnalysisRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/_authenticated/admin/portals': {
      id: '/_authenticated/admin/portals'
      path: '/admin/portals'
      fullPath: '/admin/portals'
      preLoaderRoute: typeof AuthenticatedAdminPortalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/health-portals': {
      id: '/_authenticated/admin/health-portals'
      path: '/admin/health-portals'
      fullPath: '/admin/health-portals'
      preLoaderRoute: typeof AuthenticatedAdminHealthPortalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant/screens/': {
      id: '/_authenticated/assistant/screens/'
      path: '/'
      fullPath: '/assistant/screens/'
      preLoaderRoute: typeof AuthenticatedAssistantScreensIndexRouteImport
      parentRoute: typeof AuthenticatedAssistantScreensRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-linked-permits': {
      id: '/api/public/hooks/refresh-linked-permits'
      path: '/api/public/hooks/refresh-linked-permits'
      fullPath: '/api/public/hooks/refresh-linked-permits'
      preLoaderRoute: typeof ApiPublicHooksRefreshLinkedPermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant/screens/$id': {
      id: '/_authenticated/assistant/screens/$id'
      path: '/$id'
      fullPath: '/assistant/screens/$id'
      preLoaderRoute: typeof AuthenticatedAssistantScreensIdRouteImport
      parentRoute: typeof AuthenticatedAssistantScreensRoute
    }
  }
}

interface AuthenticatedAssistantScreensRouteChildren {
  AuthenticatedAssistantScreensIdRoute: typeof AuthenticatedAssistantScreensIdRoute
  AuthenticatedAssistantScreensIndexRoute: typeof AuthenticatedAssistantScreensIndexRoute
}

const AuthenticatedAssistantScreensRouteChildren: AuthenticatedAssistantScreensRouteChildren =
  {
    AuthenticatedAssistantScreensIdRoute: AuthenticatedAssistantScreensIdRoute,
    AuthenticatedAssistantScreensIndexRoute:
      AuthenticatedAssistantScreensIndexRoute,
  }

const AuthenticatedAssistantScreensRouteWithChildren =
  AuthenticatedAssistantScreensRoute._addFileChildren(
    AuthenticatedAssistantScreensRouteChildren,
  )

interface AuthenticatedAssistantRouteChildren {
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedAssistantAnalysisRoute: typeof AuthenticatedAssistantAnalysisRoute
  AuthenticatedAssistantScreensRoute: typeof AuthenticatedAssistantScreensRouteWithChildren
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
}

const AuthenticatedAssistantRouteChildren: AuthenticatedAssistantRouteChildren =
  {
    AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
    AuthenticatedAssistantAnalysisRoute: AuthenticatedAssistantAnalysisRoute,
    AuthenticatedAssistantScreensRoute:
      AuthenticatedAssistantScreensRouteWithChildren,
    AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  }

const AuthenticatedAssistantRouteWithChildren =
  AuthenticatedAssistantRoute._addFileChildren(
    AuthenticatedAssistantRouteChildren,
  )

interface AuthenticatedJurisdictionsRouteChildren {
  AuthenticatedJurisdictionsSlugRoute: typeof AuthenticatedJurisdictionsSlugRoute
}

const AuthenticatedJurisdictionsRouteChildren: AuthenticatedJurisdictionsRouteChildren =
  {
    AuthenticatedJurisdictionsSlugRoute: AuthenticatedJurisdictionsSlugRoute,
  }

const AuthenticatedJurisdictionsRouteWithChildren =
  AuthenticatedJurisdictionsRoute._addFileChildren(
    AuthenticatedJurisdictionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHealthPortalsRoute: typeof AuthenticatedHealthPortalsRoute
  AuthenticatedJurisdictionsRoute: typeof AuthenticatedJurisdictionsRouteWithChildren
  AuthenticatedLookupRoute: typeof AuthenticatedLookupRoute
  AuthenticatedPortalsRoute: typeof AuthenticatedPortalsRoute
  AuthenticatedPropertyRoute: typeof AuthenticatedPropertyRoute
  AuthenticatedAdminHealthPortalsRoute: typeof AuthenticatedAdminHealthPortalsRoute
  AuthenticatedAdminPortalsRoute: typeof AuthenticatedAdminPortalsRoute
  AuthenticatedInspectionsIdRoute: typeof AuthenticatedInspectionsIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHealthPortalsRoute: AuthenticatedHealthPortalsRoute,
  AuthenticatedJurisdictionsRoute: AuthenticatedJurisdictionsRouteWithChildren,
  AuthenticatedLookupRoute: AuthenticatedLookupRoute,
  AuthenticatedPortalsRoute: AuthenticatedPortalsRoute,
  AuthenticatedPropertyRoute: AuthenticatedPropertyRoute,
  AuthenticatedAdminHealthPortalsRoute: AuthenticatedAdminHealthPortalsRoute,
  AuthenticatedAdminPortalsRoute: AuthenticatedAdminPortalsRoute,
  AuthenticatedInspectionsIdRoute: AuthenticatedInspectionsIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ShareReportsTokenRoute: ShareReportsTokenRoute,
  ApiPublicHooksRefreshLinkedPermitsRoute:
    ApiPublicHooksRefreshLinkedPermitsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
